### ISSUE TITLE
Version compatibility issues with M1 Macs

### ISSUE THREAD

**Issue by pooriajr** [thoughtbot-upcase-exercises/advanced-activerecord-querying-belongs_to-associations#5]
These exercises call for an old ruby version that doesn't play nicely with M1 Macs. Even when I managed to get the old ruby version installed, almost every gem had issues installing as well.

I eventually got it working by:
- Deleting the Gemfile.lock
- Changing the ruby version in the `Gemfile` and in `.ruby_version` to my current version (2.7.4 in my case)
- Adding a `[7.0]` to the end of the first line of the schema so it looks like this ->  `class CreateSchema < ActiveRecord::Migration[7.0]`
- And then running `bundle install` and `bin/setup`

I don't know if this will work for others, but I just wanted to leave this here in case it helps.

**Comment by typhoon2099** [comment]
Thanks, that was very helpful! These tutorial repos look pretty dead, it's a shame they aren't being upgraded to keep up with the latest Ruby/Gem versions...

**Comment by ioups** [comment]
Thank you for this tip ! helped me too ! I really wanted to give a shot at the exercices ✌️

**Comment by Tresor11** [comment]
I think this was fixed in #1
